### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Sander3003** [robidev/iec61850_inputs#4]
Hi Robin, I do get an issue with running docker compose in Ubuntu 18.04 LTS:
![image](https://user-images.githubusercontent.com/7427358/79600905-3a790880-80e8-11ea-8992-e7d95b5fa966.png)

Docker version 19.03.8
docker-compose version 1.18.0

Any suggestions?

**Comment by robidev** [comment]
Its actually due to the docekr version of ubuntu LTS, that does not support the newest compose version. As for compatibility sake, I just updated the repo and downgraded the version for the file to 3.3, so it should work now.
